<?php $helper = Mage::helper('lengow_connector'); ?>

<h3>SAS Lengow</h3>
<?php echo $helper->__('legals.screen.simplified_company'); ?>
<br />
<?php echo $helper->__('legals.screen.social_capital'); ?>
368 778 €
<br />
<?php echo $helper->__('legals.screen.cnil_declaration'); ?>
1748784 v 0
<br />
<?php echo $helper->__('legals.screen.company_registration_number'); ?>
513 381 434
<br />
<?php echo $helper->__('legals.screen.vat_identification_number'); ?>
FR42513381434
<br />
<br />
<h3><?php echo $helper->__('legals.screen.address'); ?></h3>
6 rue René Viviani<br />
44200 Nantes
<br />
<br />
<h3><?php echo $helper->__('legals.screen.contact'); ?></h3>
contact@lengow.com<br />
+33 (0)2 85 52 64 14
<br />
<br />
<h3><?php echo $helper->__('legals.screen.hosting'); ?></h3>
Linkbynet<br />
RCS Bobigny : 430 359 927<br />
5-9 Rue, de l’Industrie – 93200 Saint-Denis<br />
+33 (0)1 48 13 00 00
