<?php
/**
 * @var $this Lengow_Connector_Block_Adminhtml_Main
 * @see Lengow_Connector_Block_Adminhtml_Main
 */
?>

<div class="lgw-content-section">
    <h2><?php echo $this->_helper->__('connection.catalog.failed_title'); ?></h2>
</div>
<div class="lgw-module-illu mod-disconnected">
    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>connected-magento.png"
         class="lgw-module-illu-module mod-disconnected"
         alt="magento">
    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>connected-lengow.png"
         class="lgw-module-illu-lengow mod-disconnected"
         alt="lengow">
    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>unplugged.png"
         class="lgw-module-illu-plug mod-disconnected"
         alt="unplugged">
</div>
<div class="lgw-content-section">
    <p><?php echo $this->_helper->__('connection.catalog.failed_description_first'); ?></p>
    <p><?php echo $this->_helper->__('connection.catalog.failed_description_second'); ?></p>
    <p>
        <?php echo $this->_helper->__('connection.cms.failed_help'); ?>
        <a href="<?php echo $this->_pluginLinks[Lengow_Connector_Helper_Sync::LINK_TYPE_HELP_CENTER]; ?>" target="_blank">
            <?php echo $this->_helper->__('connection.cms.failed_help_center'); ?>
        </a>
        <?php echo $this->_helper->__('connection.cms.failed_help_or'); ?>
        <a href="<?php echo $this->getSupportLink(); ?>" target="_blank">
            <?php echo $this->_helper->__('connection.cms.failed_help_customer_success_team'); ?>
        </a>
    </p>
</div>
<div>
    <button class="lgw-btn lgw-btn-green js-go-to-catalog" data-retry="true">
        <?php echo $this->_helper->__('connection.cms.failed_button'); ?>
    </button>
    <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_dashboard/'); ?>"
       class="lgw-btn lgw-btn-green">
        <?php echo $this->_helper->__('connection.cms.success_button'); ?>
    </a>
</div>
