<?php
    /** @var Lengow_Connector_Helper_Data $helper */
    $helper = Mage::helper('lengow_connector');
    $stats = Mage::helper('lengow_connector/sync')->getStatistic();
    $totalOrder = isset($stats['total_order']) ? $stats['total_order'] : 0;
    $nbOrder = isset($stats['nb_order']) ? $stats['nb_order'] : 0;
    $orderToBeSent = Mage::getModel('lengow/import_order')->countOrderToBeSent();
?>

<div class="lgw-container">
    <div class="lgw-box lgw-home-header text-center">
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>lengow-white-big.png" alt="lengow">
        <h1><?php echo $helper->__('dashboard.screen.welcome_back'); ?></h1>
        <a href="http://my.lengow.io/" class="lgw-btn" target="_blank" title="<?php echo $helper->__('dashboard.screen.go_to_lengow'); ?>">
            <?php echo $helper->__('dashboard.screen.go_to_lengow'); ?>
        </a>
    </div>
    <div class="lgw-row lgw-home-menu text-center">
        <div class="lgw-col-4">
            <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_product/'); ?>" class="lgw-box-link" title="<?php echo $helper->__('dashboard.screen.products_title'); ?>">
                <div class="lgw-box">
                    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>home-products.png" class="img-responsive">
                    <h2><?php echo $helper->__('dashboard.screen.products_title'); ?></h2>
                    <p><?php echo $helper->__('dashboard.screen.products_text'); ?></p>
                </div>
            </a>
        </div>
        <div class="lgw-col-4">
            <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>" class="lgw-box-link" title="<?php echo $helper->__('dashboard.screen.orders_title'); ?>">
                <div class="lgw-box">
                    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>home-orders.png" class="img-responsive">
                    <h2>
                        <?php echo $helper->__('dashboard.screen.orders_title'); ?>
                        <?php if( $orderToBeSent > 0 ) { ?>
                            <span class="lgw-label lgw-label red"><?php echo $orderToBeSent; ?></span>
                        <?php } ?>
                    </h2>
                    <p><?php echo $helper->__('dashboard.screen.orders_text'); ?></p>
                </div>
            </a>
        </div>
        <div class="lgw-col-4">
            <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/system_config/edit/section/lengow_global_options'); ?>" class="lgw-box-link" title="<?php echo $helper->__('dashboard.screen.settings_title'); ?>">
                <div class="lgw-box">
                    <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>home-settings.png" class="img-responsive">
                    <h2><?php echo $helper->__('dashboard.screen.settings_title'); ?></h2>
                    <p><?php echo $helper->__('dashboard.screen.settings_text'); ?></p>
                </div>
            </a>
        </div>
    </div>
    <?php if($stats['available']) { ?>
    <div class="lgw-box text-center">
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>picto-stats.png" class="img-responsive">
        <h2><?php echo $helper->__('dashboard.screen.partner_business'); ?></h2>
        <div class="lgw-row lgw-home-stats">
            <div class="lgw-col-4 lgw-col-offset-2">
                <h5><?php echo $helper->__('dashboard.screen.stat_turnover'); ?></h5>
                <span class="stats-big-value"><?php echo $totalOrder; ?></span>
            </div>
            <div class="lgw-col-4">
                <h5><?php echo $helper->__('dashboard.screen.stat_nb_orders'); ?></h5>
                <span class="stats-big-value"><?php echo $nbOrder; ?></span>
            </div>
        </div>
        <p>
            <a href="http://my.lengow.io/" target="_blank"
                title="<?php echo $helper->__('dashboard.screen.stat_more_stats'); ?>" class="lgw-btn lgw-btn-white">
                <?php echo $helper->__('dashboard.screen.stat_more_stats'); ?>
            </a>
        </p>
    </div>
    <?php } ?>
    <div class="lgw-box">
        <h2><?php echo $helper->__('dashboard.screen.some_help_title'); ?></h2>
        <p>
            <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_help/'); ?>"
                title="<?php echo $helper->__('dashboard.screen.get_in_touch'); ?>">
                <?php echo $helper->__('dashboard.screen.get_in_touch'); ?>
            </a>
        </p>
        <p>
            <a href="<?php echo $helper->__('help.screen.knowledge_link_url'); ?>" target="_blank"
                title="<?php echo $helper->__('dashboard.screen.visit_help_center'); ?>"><?php echo $helper->__('dashboard.screen.visit_help_center'); ?></a>
            <?php echo $helper->__('dashboard.screen.configure_plugin'); ?>
        </p>
    </div>
</div>