<?php
/**
 * @var $this Lengow_Connector_Block_Adminhtml_Home_Content
 * @see Lengow_Connector_Block_Adminhtml_Home_Content
 */
?>

<div id="lgw-connection-home">
    <div class="lgw-content-section">
        <p><?php echo $this->_helper->__('connection.home.description_first'); ?></p>
        <p><?php echo $this->_helper->__('connection.home.description_second'); ?></p>
        <p><?php echo $this->_helper->__('connection.home.description_third'); ?></p>
    </div>
    <div class="lgw-module-illu">
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>connected-magento.png"
             class="lgw-module-illu-module"
             alt="magento">
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>connected-lengow.png"
             class="lgw-module-illu-lengow"
             alt="lengow">
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>plug-grey.png"
             class="lgw-module-illu-plug"
             alt="plug">
    </div>
    <p><?php echo $this->_helper->__('connection.home.description_fourth'); ?></p>
    <div>
        <button class="lgw-btn lgw-btn-green js-go-to-credentials">
            <?php echo $this->_helper->__('connection.home.button'); ?>
        </button>
        <br/>
        <p>
            <?php echo $this->_helper->__('connection.home.no_account'); ?>
            <a href="<?php echo $this->getLengowSolutionUrl(); ?>" target="_blank">
                <?php echo $this->_helper->__('connection.home.no_account_sign_up'); ?>
            </a>
        </p>
    </div>
</div>
