<?php
$helper = Mage::helper('lengow_connector');
$account = Mage::helper('lengow_connector/sync')->getStatusAccount();
$status = ($account['type'] == 'free_trial') ? 'free_trial' : 'bad_payer';
$left_day = $account['day'];
?>

<div class="lgw-container">
    <div>
        <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>lengow-white-big.png" alt="lengow">
        <?php if ($status == 'free_trial' && $left_day == 0) : ?>
            <h1><?php echo $helper->__('status.screen.title_end_free_trial'); ?></h1>
            <h4><?php echo $helper->__('status.screen.subtitle_end_free_trial'); ?></h4>
            <p><?php echo $helper->__('status.screen.first_description_end_free_trial'); ?></p>
            <p><?php echo $helper->__('status.screen.second_description_end_free_trial'); ?></p>
            <p><?php echo $helper->__('status.screen.third_description_end_free_trial'); ?></p>
            <button type="button" class="lgw-btn">
                <a href="http://www.lengow.com/">
                    <?php echo Mage::helper('lengow_connector')->__('status.screen.facturation_button'); ?>
                </a>
            </button>
            <button type="button">
                <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_home/reFresh/'); ?>">
                    <?php echo Mage::helper('lengow_connector')->__('status.screen.refresh_action'); ?>
                </a>
            </button>
        <?php else : ?>
            <h1><?php echo $helper->__('status.screen.title_bad_payer'); ?></h1>
            <h4><?php echo $helper->__('status.screen.subtitle_bad_payer'); ?></h4>
            <p><?php echo $helper->__('status.screen.first_description_bad_payer'); ?></p>
            <p><?php echo $helper->__('status.screen.second_description_bad_payer'); ?>
                <a href="mailto:backoffice@lengow.com">backoffice@lengow.com</a>
                <?php echo $helper->__('status.screen.phone_bad_payer'); ?>
            </p>
            <p><?php echo $helper->__('status.screen.third_description_bad_payer'); ?></p>
            <button type="button" class="lgw-btn">
                <a href="http://www.lengow.com/">
                    <?php echo Mage::helper('lengow_connector')->__('status.screen.upgrade_account_button'); ?>
                </a>
            </button>
            <button type="button">
                <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_home/reFresh/'); ?>">
                    <?php echo Mage::helper('lengow_connector')->__('status.screen.refresh_action'); ?>
                </a>
            </button>
        <?php endif; ?>
    </div>
</div>