<?php
    /** @var Lengow_Connector_Helper_Data $helper */
    $helper = Mage::helper('lengow_connector');
?>

<div class="lgw-box">
    <div class="text-center">
        <h2><?php echo $helper->__('help.screen.title'); ?></h2>
        <p>
            <?php echo $helper->__('help.screen.contain_text_support')?>
            <a href="<?php echo $helper->__('help.screen.link_lengow_support') ?>" target="_blank" title="Lengow Support">
                <?php echo $helper->__('help.screen.title_lengow_support') ?>
            </a>
        </p>
        <p><?php echo $helper->__('help.screen.contain_text_support_hour'); ?></p>
        <p><?php echo $helper->__('help.screen.find_answer'); ?>
            <a href="<?php echo $helper->__('help.screen.knowledge_link_url'); ?>" class="sub-link" target="_blank" title="Help Center">
                <?php echo $helper->__('help.screen.link_magento_guide'); ?>
            </a>
        </p>
    </div>
</div>

