<?php $helper = Mage::helper('lengow_connector'); ?>
<div id="footer" class="lgw-footer">
    <div class="pull-right">
        <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_toolbox/'); ?>"
            class="sub-link" title="<?php echo $helper->__('footer.toolbox') ?>"><?php echo $helper->__('footer.toolbox') ?></a>
        |
        <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_legal/'); ?>"
            class="sub-link" title="<?php echo $helper->__('footer.legals') ?>"><?php echo $helper->__('footer.legals') ?></a>
        |
        Lengow Magento Module - 
        <a href="http://www.lengow.com" class="sub-link" title="Lengow.com" target="_blank">Lengow.com</a> 
        <?php /*echo $helper->__('footer.copyright_lengow')*/ ?>
    </div>
</div>
