<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">

<link rel="stylesheet" type="text/css"
      href="/skin/adminhtml/default/default/lengow/css/lengow.css"
      media="all">

<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/lengow_log'); ?>"><?php echo $this->__('Logs') ?> </a></li>
    <li role="presentation"><a href="#">Profile</a></li>
    <li role="presentation"><a href="#">Messages</a></li>
</ul>
