<div class="lgw-container lgw-connection text-center">
    <div class="lgw-content-section">
        <div class="lgw-logo">
            <img src="<?php echo $this->getSkinUrl('lengow/images/') ?>lengow-blue.png" alt="lengow">
        </div>
    </div>
    <div id="lgw-connection-content">
        <?php echo $this->getChildHtml('lengow_home'); ?>
    </div>
</div>
<input type="hidden"
       id="lengow_ajax_link"
       value="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_home/'); ?>?isAjax=true"
>
<?php echo $this->getChildHtml('lengow_footer'); ?>
