<?php echo $this->getChildHtml("lengow_header"); ?>
<h1>Product Layout</h1>
<script type="text/javascript" src="<?php echo Mage::getDesign()->getSkinUrl();?>lengow/js/bootstrap-switch.js"></script>
<script type="text/javascript" src="<?php echo Mage::getDesign()->getSkinUrl();?>lengow/js/select2.js"></script>
<script type="text/javascript" src="<?php echo Mage::getDesign()->getSkinUrl();?>lengow/js/product.js"></script>
<?php
    echo $this->getChildHtml("lengow_product");
    echo $this->getChildHtml("lengow_content");
    echo $this->getChildHtml("lengow_footer");