<?php
    $helper = Mage::helper('lengow_connector');
    $configHelper = Mage::helper('lengow_connector/config');
    $importHelper = Mage::helper('lengow_connector/import');
    $lastImport = $importHelper->getLastImport();
    $reportMailActive = (bool)$configHelper->get('report_mail_enable');
    $reportMailLink = Mage::helper('adminhtml')
        ->getUrl('adminhtml/system_config/edit/section/lengow_import_options/');
    $reportMails = $configHelper->getReportEmailAddress();
    $order = Mage::getModel('lengow/import_order');
    $seeMigrateBlock = (bool)$configHelper->get('see_migrate_block');
    $nbOrderImported = $order->countOrderImportedByLengow();
    $orderNotMigrate = $order->countNotMigrateOrder(false);
    $orderWithError = $order->countOrderWithError();
    $orderToBeSent = $order->countOrderToBeSent();
?>

<div class="lgw-box">
    <?php if ((bool)$configHelper->get('preprod_mode_enable')) { ?>
        <p class="blue_frame" style="line-height: 20px;">
            <?php echo $helper->__('order.screen.preprod_warning_message', array('url' => $reportMailLink)); ?>
        </p>
    <?php } ?>
    <?php if ($seeMigrateBlock && $orderNotMigrate > 0) { ?>
        <div id="lengow_migrate_order" class="blue_frame">
            <p><?php echo $helper->__('order.screen.nb_old_order_imported', array('nb_order' => $nbOrderImported)); ?></p>
            <p><?php echo $helper->__('order.screen.order_visible_in_page', array('nb_order' => $orderToBeSent)); ?></p>
            <p><?php echo $helper->__('order.screen.where_see_old_order'); ?></p>
            <button
                type="button" 
                id="lengow_migrate_fade"
                class="lgw-btn " 
                data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
                <?php echo $helper->__('order.screen.button_migrate'); ?>
            </button>
        </div>
    <?php } ?>
    <div class="lgw-col-8">
        <p id="lengow_order_with_error">
            <?php echo $helper->__('order.screen.order_with_error', array('nb_order' => $orderWithError)); ?>
        </p>
        <p id="lengow_order_to_be_sent">
            <?php echo $helper->__('order.screen.order_to_be_sent', array('nb_order' => $orderToBeSent)); ?>
        </p>
        <p id="lengow_last_importation">
            <?php
            if ($lastImport['type'] != 'none') {
                echo $helper->__('order.screen.last_order_importation', array(
                    'last_importation' => '<b>'.$helper->getDateInCorrectFormat($lastImport['timestamp']).'</b>'
                ));
            } else {
                echo $helper->__('order.screen.no_order_importation');
            }
            ?>
        </p>
        <p>
            <?php
            if ($reportMailActive) {
                echo $helper->__('order.screen.all_order_will_be_sent_to').' ';
                echo implode(', ', $reportMails).' ';
            } else {
                echo $helper->__('order.screen.no_order_will_be_sent').' ';
            }
            echo '(<a href="'.$reportMailLink.'">'.$helper->__('order.screen.change_this').'</a>)';
            ?>
        </p>
    </div>
    <div class="lgw-col-4 pull-right text-right">
        <button
            type="button"
            id="lengow_import_orders"
            class="lgw-btn"
            data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
            <?php echo $helper->__('order.screen.button_import'); ?>
        </button>
    </div>
    <div class="clearfix"></div>
    <div id="lengow_wrapper_messages" class="blue_frame" style="display:none;"></div>
    <div id="lengow_wrapper_timeout" class="red_frame" style="display:none;">
        <?php echo $helper->__('order.screen.ajax_timeout'); ?>
    </div>
    <div id="lengow_controller_url"
        data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
    </div>
</div>
