<?php
    $helper = Mage::helper('lengow_connector');
    $config_helper = Mage::helper('lengow_connector/config');
    $import_helper = Mage::helper('lengow_connector/import');

    $last_import = $import_helper->getLastImport();
    $last_import_date = $helper->getDateInLocalDate($last_import['timestamp']);

    $report_mail_active = (bool)$config_helper->get('report_mail_enable');
    $report_mail_link = Mage::helper('adminhtml')
        ->getUrl('adminhtml/system_config/edit/section/lengow_import_options/');
    $report_mails = explode(';', $config_helper->get('report_mail_address'));

    $order = Mage::getModel('lengow/import_order');
    $old_orders = $order->countNotMigrateOrder();
    $order_with_error = $order->countOrderWithError();
    $order_to_be_sent = $order->countOrderToBeSent();
?>

<h2><?php echo $helper->__('menu.orders'); ?></h2>

<p id="lengow_order_with_error">
    <?php echo $helper->__('order.screen.order_with_error', array('nb_order' => $order_with_error)); ?>
</p>
<p id="lengow_order_to_be_sent">
    <?php echo $helper->__('order.screen.order_to_be_sent', array('nb_order' => $order_to_be_sent)); ?>
</p>
<p id="lengow_last_importation">
    <?php
    if ($last_import['type'] != 'none') {
        echo $helper->__('order.screen.last_order_importation', array(
            'last_importation' => '<b>'.$last_import_date.'</b>'
        ));
    } else {
        echo $helper->__('order.screen.no_order_importation');
    }
    ?>
</p>
<p>
    <?php
    if ($report_mail_active) {
        echo $helper->__('order.screen.all_order_will_be_sent_to').' ';
        echo implode(', ', $report_mails).' ';
    } else {
        echo $helper->__('order.screen.no_order_will_be_sent').' ';
    }
    echo '(<a href="'.$report_mail_link.'">'.$helper->__('order.screen.change_this').'</a>)';
    ?>
</p>

<button
    type="button"
    id="lengow_import_orders"
    class="lengow_btn"
    data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
    <?php echo $helper->__('order.screen.button_import'); ?>
</button>
<?php if ($old_orders == 0) { ?>
    <button
        type="button" 
        id="lengow_migrate_order"
        class="lengow_btn"
        data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
        <?php echo $helper->__('order.screen.button_migrate'); ?>
    </button>
<?php } ?>

<div id="lengow_wrapper_messages" class="blue_frame" style="display:none;"></div>

<div id="lengow_controller_url"
    data-href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/lengow_order/'); ?>?isAjax=true" >
</div>
