<!-- Tag_Lengow -->
<img
    src="https://trk.lgw.io/lead?account_id=<?php echo $this->getData('account_id'); ?>&order_ref=<?php echo $this->getData('order_ref'); ?>&amount=<?php echo $this->getData('amount'); ?>&currency=<?php echo $this->getData('currency'); ?>&payment_method=<?php echo $this->getData('payment_method'); ?>&cart=<?php echo $this->getData('cart'); ?>&cart_number=<?php echo $this->getData('cart_number'); ?>&newbiz=<?php echo $this->getData('newbiz'); ?>"
    alt="" style="width: 1px; height: 1px; border: none;"/>
<img
    src="https://trk.lgw.io/validation?account_id=<?php echo $this->getData('account_id'); ?>&order_ref=<?php echo $this->getData('order_ref'); ?>&payment_method=<?php echo $this->getData('payment_method'); ?>&valid=<?php echo $this->getData('valid'); ?>"
    alt="" style="width: 1px; height: 1px; border: none;"/>
<!-- /Tag_Lengow -->
